version: "3"

services:

  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - fastapi-postgres-db-volume:/var/lib/postgresql/data
    ports:
      - 5433:5432
    healthcheck:
      test: "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"
      interval: 5s
      retries: 5
    restart: always

  backend:
    build:
        context: .
        dockerfile: ./back/Dockerfile
    environment:
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - SECRET_KEY=${SECRET_KEY}
      - MAIL_USERNAME=${MAIL_USERNAME}
      - MAIL_PASSWORD=${MAIL_PASSWORD}
      - MAIL_FROM=${MAIL_FROM}
      - MAIL_PORT=${MAIL_PORT}
      - MAIL_SERVER=${MAIL_SERVER}
      - MAIL_TLS=${MAIL_TLS}
      - MAIL_SSL=${MAIL_SSL}
      - MAIL_STARTTLS=${MAIL_STARTTLS}
      - MAIL_SSL_TLS=${MAIL_SSL_TLS}
      - USE_CREDENTIALS=${USE_CREDENTIALS}
      - VALIDATE_CERTS=${VALIDATE_CERTS}
    ports:
      - 8000:8000
    depends_on:
      - postgres
    restart: always
  
  frontend:
    build:
        context: .
        dockerfile: ./front/Dockerfile
    ports:
      - 8081:8081
    depends_on:
      - postgres
    restart: always
  
volumes:
  fastapi-postgres-db-volume: